from PyQt5 import QtCore, QtGui, QtWidgets


class Settings_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.language_text = QtWidgets.QLabel(self.centralwidget)
        self.language_text.setGeometry(QtCore.QRect(0, 100, 181, 20))
        self.language_text.setObjectName("language_text")
        self.language = QtWidgets.QComboBox(self.centralwidget)
        self.language.setGeometry(QtCore.QRect(180, 100, 69, 22))
        self.language.setObjectName("language")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.btn_exit.setObjectName("btn_exit")
        self.confirmation_text = QtWidgets.QLabel(self.centralwidget)
        self.confirmation_text.setGeometry(QtCore.QRect(0, 130, 91, 16))
        self.confirmation_text.setObjectName("confirmation_text")
        self.confirmation = QtWidgets.QComboBox(self.centralwidget)
        self.confirmation.setGeometry(QtCore.QRect(180, 130, 69, 22))
        self.confirmation.setObjectName("confirmation")
        self.btn_clear_all_trailers = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_all_trailers.setGeometry(QtCore.QRect(660, 60, 131, 23))
        self.btn_clear_all_trailers.setObjectName("btn_clear_all_trailers")
        self.btn_clear_all_images = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_all_images.setGeometry(QtCore.QRect(660, 30, 131, 23))
        self.btn_clear_all_images.setObjectName("btn_clear_all_images")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.language_text.setText(_translate("MainWindow", "Язык(Тест функция не доделана)"))
        self.btn_exit.setText(_translate("MainWindow", "<- Назад"))
        self.confirmation_text.setText(_translate("MainWindow", "Подтверждение "))
        self.btn_clear_all_trailers.setText(_translate("MainWindow", "Очистить Трейлеры"))
        self.btn_clear_all_images.setText(_translate("MainWindow", "Очистить изображения"))


class Serials_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 973)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(660, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_exit_serials = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_serials.setGeometry(QtCore.QRect(20, 0, 51, 23))
        self.btn_exit_serials.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_exit_serials.setObjectName("btn_exit_serials")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.btn_main_criterias = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.btn_main_criterias.setContentsMargins(0, 0, 0, 0)
        self.btn_main_criterias.setObjectName("btn_main_criterias")
        self.btn_date_DESC_serials = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_date_DESC_serials.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.btn_date_DESC_serials.setObjectName("btn_date_DESC_serials")
        self.btn_main_criterias.addWidget(self.btn_date_DESC_serials)
        self.btn_name_DESC_serials = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_name_DESC_serials.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_name_DESC_serials.setObjectName("btn_name_DESC_serials")
        self.btn_main_criterias.addWidget(self.btn_name_DESC_serials)
        self.btn_rating_DESC_serials = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_rating_DESC_serials.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_rating_DESC_serials.setObjectName("btn_rating_DESC_serials")
        self.btn_main_criterias.addWidget(self.btn_rating_DESC_serials)
        self.table_serials = QtWidgets.QListWidget(self.centralwidget)
        self.table_serials.setGeometry(QtCore.QRect(350, 620, 521, 351))
        self.table_serials.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_serials.setStyleSheet("background-color: rgba(109, 230, 138, 255);")
        self.table_serials.setObjectName("table_serials")
        self.table_description_serials = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.table_description_serials.setGeometry(QtCore.QRect(10, 770, 321, 261))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_description_serials.setFont(font)
        self.table_description_serials.setStyleSheet("background-color: rgba(109, 230, 138, 255);")
        self.table_description_serials.setReadOnly(True)
        self.table_description_serials.setObjectName("table_description_serials")
        self.categories = QtWidgets.QToolBox(self.centralwidget)
        self.categories.setGeometry(QtCore.QRect(350, 400, 521, 211))
        self.categories.setStyleSheet("background-color: rgba(109, 230, 138, 255);")
        self.categories.setObjectName("categories")
        self.categoriesPage1 = QtWidgets.QWidget()
        self.categoriesPage1.setGeometry(QtCore.QRect(0, 0, 521, 157))
        self.categoriesPage1.setObjectName("categoriesPage1")
        self.categories.addItem(self.categoriesPage1, "")
        self.categoriesPage2 = QtWidgets.QWidget()
        self.categoriesPage2.setGeometry(QtCore.QRect(0, 0, 521, 157))
        self.categoriesPage2.setObjectName("categoriesPage2")
        self.widget = QtWidgets.QWidget(self.categoriesPage2)
        self.widget.setGeometry(QtCore.QRect(10, 0, 501, 41))
        self.widget.setObjectName("widget")
        self.categories_2 = QtWidgets.QHBoxLayout(self.widget)
        self.categories_2.setContentsMargins(0, 0, 0, 0)
        self.categories_2.setObjectName("categories_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.categories_2.addWidget(self.checkBox)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.categories_2.addWidget(self.checkBox_5)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.categories_2.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.categories_2.addWidget(self.checkBox_2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.categories_2.addWidget(self.checkBox_4)
        self.layoutWidget_2 = QtWidgets.QWidget(self.categoriesPage2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 501, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.categories_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.categories_3.setContentsMargins(0, 0, 0, 0)
        self.categories_3.setObjectName("categories_3")
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.categories_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.categories_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_8.setObjectName("checkBox_8")
        self.categories_3.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.categories_3.addWidget(self.checkBox_9)
        self.categories.addItem(self.categoriesPage2, "")
        self.input_search_serials = QtWidgets.QLineEdit(self.centralwidget)
        self.input_search_serials.setGeometry(QtCore.QRect(350, 40, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.input_search_serials.setFont(font)
        self.input_search_serials.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_search_serials.setToolTipDuration(-1)
        self.input_search_serials.setAutoFillBackground(False)
        self.input_search_serials.setStyleSheet("border-radius: 10;")
        self.input_search_serials.setObjectName("input_search_serials")
        self.widget_123 = QtWidgets.QWidget(self.centralwidget)
        self.widget_123.setGeometry(QtCore.QRect(30, 90, 321, 661))
        self.widget_123.setObjectName("widget_123")
        self.image_serials = QtWidgets.QLabel(self.widget_123)
        self.image_serials.setGeometry(QtCore.QRect(20, 40, 291, 431))
        self.image_serials.setStyleSheet("background-color: rgba(109, 230, 138, 255);")
        self.image_serials.setText("")
        self.image_serials.setObjectName("image_serials")
        self.description = QtWidgets.QLabel(self.widget_123)
        self.description.setGeometry(QtCore.QRect(10, 640, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setObjectName("description")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_123)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 105, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.requests_film = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.requests_film.setContentsMargins(0, 0, 0, 0)
        self.requests_film.setObjectName("requests_film")
        self.rating_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rating_films.setFont(font)
        self.rating_films.setObjectName("rating_films")
        self.requests_film.addWidget(self.rating_films)
        self.nation_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nation_films.setFont(font)
        self.nation_films.setObjectName("nation_films")
        self.requests_film.addWidget(self.nation_films)
        self.style_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.style_films.setFont(font)
        self.style_films.setObjectName("style_films")
        self.requests_film.addWidget(self.style_films)
        self.age_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.age_films.setFont(font)
        self.age_films.setObjectName("age_films")
        self.requests_film.addWidget(self.age_films)
        self.date_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.date_films.setFont(font)
        self.date_films.setObjectName("date_films")
        self.requests_film.addWidget(self.date_films)
        self.series_film = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.series_film.setFont(font)
        self.series_film.setObjectName("series_film")
        self.requests_film.addWidget(self.series_film)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.requests_film.addWidget(self.label_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_123)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 470, 141, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.output_film = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.output_film.setContentsMargins(0, 0, 9, 0)
        self.output_film.setObjectName("output_film")
        self.output_rating_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_rating_films.setStyleSheet("")
        self.output_rating_films.setText("")
        self.output_rating_films.setObjectName("output_rating_films")
        self.output_film.addWidget(self.output_rating_films)
        self.output_nation_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_nation_films.setStyleSheet("")
        self.output_nation_films.setText("")
        self.output_nation_films.setObjectName("output_nation_films")
        self.output_film.addWidget(self.output_nation_films)
        self.output_style_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_style_films.setStyleSheet("")
        self.output_style_films.setText("")
        self.output_style_films.setObjectName("output_style_films")
        self.output_film.addWidget(self.output_style_films)
        self.output_age_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_age_films.setStyleSheet("")
        self.output_age_films.setText("")
        self.output_age_films.setObjectName("output_age_films")
        self.output_film.addWidget(self.output_age_films)
        self.output_date_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_date_films.setStyleSheet("")
        self.output_date_films.setText("")
        self.output_date_films.setObjectName("output_date_films")
        self.output_film.addWidget(self.output_date_films)
        self.output_seasons_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_seasons_films.setText("")
        self.output_seasons_films.setObjectName("output_seasons_films")
        self.output_film.addWidget(self.output_seasons_films)
        self.output_reg = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_reg.setText("")
        self.output_reg.setObjectName("output_reg")
        self.output_film.addWidget(self.output_reg)
        self.name_film = QtWidgets.QLabel(self.widget_123)
        self.name_film.setGeometry(QtCore.QRect(0, 0, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_film.setFont(font)
        self.name_film.setObjectName("name_film")
        self.btn_clear_serials_images = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_serials_images.setGeometry(QtCore.QRect(80, 0, 131, 23))
        self.btn_clear_serials_images.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_clear_serials_images.setObjectName("btn_clear_serials_images")
        self.ready_for_viewing = QtWidgets.QLabel(self.centralwidget)
        self.ready_for_viewing.setGeometry(QtCore.QRect(360, 70, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ready_for_viewing.setFont(font)
        self.ready_for_viewing.setText("")
        self.ready_for_viewing.setObjectName("ready_for_viewing")
        self.btn_clear_trailers = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_trailers.setGeometry(QtCore.QRect(220, 0, 121, 23))
        self.btn_clear_trailers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_clear_trailers.setObjectName("btn_clear_trailers")
        self.widget_film_trailer = QVideoWidget(self.centralwidget)
        self.widget_film_trailer.setGeometry(QtCore.QRect(350, 100, 521, 271))
        self.widget_film_trailer.setStyleSheet("background-color: rgba(109, 230, 138, 255);")
        self.widget_film_trailer.setObjectName("widget_film_trailer")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(350, 370, 521, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color: rgba(109, 230, 138, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color: rgba(109, 230, 138, 255);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 50)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout.addWidget(self.horizontalSlider_2)
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, -10, 901, 961))
        self.bg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(109, 230, 138, 255), stop:1 rgba(255, 255, 255, 255))")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.label.raise_()
        self.btn_exit_serials.raise_()
        self.horizontalLayoutWidget.raise_()
        self.table_serials.raise_()
        self.table_description_serials.raise_()
        self.categories.raise_()
        self.input_search_serials.raise_()
        self.widget_123.raise_()
        self.btn_clear_serials_images.raise_()
        self.ready_for_viewing.raise_()
        self.btn_clear_trailers.raise_()
        self.widget_film_trailer.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Сериалы"))
        self.btn_exit_serials.setText(_translate("MainWindow", "Назад"))
        self.btn_date_DESC_serials.setText(_translate("MainWindow", "По дате"))
        self.btn_name_DESC_serials.setText(_translate("MainWindow", "По названию"))
        self.btn_rating_DESC_serials.setText(_translate("MainWindow", "По рейтингу"))
        self.checkBox.setText(_translate("MainWindow", "Фантастика"))
        self.checkBox_5.setText(_translate("MainWindow", "Драма"))
        self.checkBox_3.setText(_translate("MainWindow", "Мультфильм"))
        self.checkBox_2.setText(_translate("MainWindow", "Боевик"))
        self.checkBox_4.setText(_translate("MainWindow", "фэнтези"))
        self.checkBox_6.setText(_translate("MainWindow", "Триллер"))
        self.checkBox_7.setText(_translate("MainWindow", "Детектив"))
        self.checkBox_8.setText(_translate("MainWindow", "Комедия"))
        self.checkBox_9.setText(_translate("MainWindow", "Криминал"))
        self.input_search_serials.setText(_translate("MainWindow", "Поиск...."))
        self.description.setText(_translate("MainWindow", "Описание:"))
        self.rating_films.setText(_translate("MainWindow", "Рейтинг: "))
        self.nation_films.setText(_translate("MainWindow", "Страна:"))
        self.style_films.setText(_translate("MainWindow", "Жанры:"))
        self.age_films.setText(_translate("MainWindow", "Возраст:"))
        self.date_films.setText(_translate("MainWindow", "Релиз: "))
        self.series_film.setText(_translate("MainWindow", "Сезонов:"))
        self.label_3.setText(_translate("MainWindow", "Режиссер:"))
        self.name_film.setText(_translate("MainWindow", "Сериал"))
        self.btn_clear_serials_images.setText(_translate("MainWindow", "Очистить Изображения"))
        self.btn_clear_trailers.setText(_translate("MainWindow", "Очистить трейлеры"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить Трейлер"))
        self.label_2.setText(_translate("MainWindow", "Громкость"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


class Books_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(982, 1051)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_date_DESC = QtWidgets.QPushButton(self.centralwidget)
        self.btn_date_DESC.setGeometry(QtCore.QRect(90, 50, 71, 23))
        self.btn_date_DESC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_date_DESC.setObjectName("btn_date_DESC")
        self.btn_name_DESC = QtWidgets.QPushButton(self.centralwidget)
        self.btn_name_DESC.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.btn_name_DESC.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_name_DESC.setObjectName("btn_name_DESC")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(0, 10, 75, 23))
        self.btn_exit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_exit.setObjectName("btn_exit")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 80, 481, 701))
        self.widget.setObjectName("widget")
        self.image = QtWidgets.QLabel(self.widget)
        self.image.setGeometry(QtCore.QRect(10, 40, 471, 631))
        self.image.setStyleSheet("")
        self.image.setText("")
        self.image.setObjectName("image")
        self.description = QtWidgets.QLabel(self.widget)
        self.description.setGeometry(QtCore.QRect(0, 670, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setObjectName("description")
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setGeometry(QtCore.QRect(10, 0, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.table_description = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.table_description.setGeometry(QtCore.QRect(0, 780, 481, 231))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_description.setFont(font)
        self.table_description.setStyleSheet("background-color: rgba(255, 131, 171, 255);")
        self.table_description.setReadOnly(True)
        self.table_description.setObjectName("table_description")
        self.input_search = QtWidgets.QLineEdit(self.centralwidget)
        self.input_search.setGeometry(QtCore.QRect(270, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.input_search.setFont(font)
        self.input_search.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_search.setToolTipDuration(-1)
        self.input_search.setAutoFillBackground(False)
        self.input_search.setStyleSheet("border-radius: 10;")
        self.input_search.setObjectName("input_search")
        self.categories = QtWidgets.QToolBox(self.centralwidget)
        self.categories.setGeometry(QtCore.QRect(490, 230, 491, 181))
        self.categories.setStyleSheet("background-color: rgba(255, 131, 171, 255);")
        self.categories.setObjectName("categories")
        self.categoriesPage1 = QtWidgets.QWidget()
        self.categoriesPage1.setGeometry(QtCore.QRect(0, 0, 421, 127))
        self.categoriesPage1.setObjectName("categoriesPage1")
        self.categories.addItem(self.categoriesPage1, "")
        self.categoriesPage2 = QtWidgets.QWidget()
        self.categoriesPage2.setGeometry(QtCore.QRect(0, 0, 491, 127))
        self.categoriesPage2.setObjectName("categoriesPage2")
        self.layoutWidget = QtWidgets.QWidget(self.categoriesPage2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, -10, 491, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.categories_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.categories_3.setContentsMargins(0, 0, 0, 0)
        self.categories_3.setObjectName("categories_3")
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.categories_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.categories_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.categories_3.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.categories_3.addWidget(self.checkBox_9)
        self.layoutWidget_2 = QtWidgets.QWidget(self.categoriesPage2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 40, 491, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.categories_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.categories_4.setContentsMargins(0, 0, 0, 0)
        self.categories_4.setObjectName("categories_4")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.categories_4.addWidget(self.checkBox)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.categories_4.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.categories_4.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.categories_4.addWidget(self.checkBox_12)
        self.categories.addItem(self.categoriesPage2, "")
        self.table_books = QtWidgets.QListWidget(self.centralwidget)
        self.table_books.setGeometry(QtCore.QRect(490, 420, 491, 591))
        self.table_books.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_books.setStyleSheet("background-color: rgba(255, 131, 171, 255);")
        self.table_books.setObjectName("table_books")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1421, 1031))
        self.bg.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(255, 131, 171, 255), stop:1 rgba(255, 255, 255, 255))")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.btn_clear_images = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_images.setGeometry(QtCore.QRect(80, 10, 121, 23))
        self.btn_clear_images.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_clear_images.setObjectName("btn_clear_images")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(540, 90, 141, 141))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.output = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.output.setContentsMargins(0, 0, 9, 0)
        self.output.setObjectName("output")
        self.output_author = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.output_author.setStyleSheet("")
        self.output_author.setText("")
        self.output_author.setObjectName("output_author")
        self.output.addWidget(self.output_author)
        self.output_style = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.output_style.setStyleSheet("")
        self.output_style.setText("")
        self.output_style.setObjectName("output_style")
        self.output.addWidget(self.output_style)
        self.output_date = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.output_date.setStyleSheet("")
        self.output_date.setText("")
        self.output_date.setObjectName("output_date")
        self.output.addWidget(self.output_date)
        self.output_tom = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.output_tom.setStyleSheet("")
        self.output_tom.setText("")
        self.output_tom.setObjectName("output_tom")
        self.output.addWidget(self.output_tom)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(490, 90, 105, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.requests = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.requests.setContentsMargins(0, 0, 0, 0)
        self.requests.setObjectName("requests")
        self.rating = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rating.setFont(font)
        self.rating.setObjectName("rating")
        self.requests.addWidget(self.rating)
        self.style = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.style.setFont(font)
        self.style.setObjectName("style")
        self.requests.addWidget(self.style)
        self.date = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.date.setFont(font)
        self.date.setObjectName("date")
        self.requests.addWidget(self.date)
        self.date_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.date_2.setFont(font)
        self.date_2.setObjectName("date_2")
        self.requests.addWidget(self.date_2)
        self.bg.raise_()
        self.btn_date_DESC.raise_()
        self.btn_name_DESC.raise_()
        self.btn_exit.raise_()
        self.widget.raise_()
        self.table_description.raise_()
        self.input_search.raise_()
        self.categories.raise_()
        self.table_books.raise_()
        self.label.raise_()
        self.btn_clear_images.raise_()
        self.verticalLayoutWidget_5.raise_()
        self.verticalLayoutWidget_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_date_DESC.setText(_translate("MainWindow", "По дате"))
        self.btn_name_DESC.setText(_translate("MainWindow", "По названию"))
        self.btn_exit.setText(_translate("MainWindow", "Назад"))
        self.description.setText(_translate("MainWindow", "Описание:"))
        self.name.setText(_translate("MainWindow", "Книга"))
        self.input_search.setText(_translate("MainWindow", "Поиск...."))
        self.checkBox_6.setText(_translate("MainWindow", "Образование"))
        self.checkBox_7.setText(_translate("MainWindow", "Машинное обучение"))
        self.checkBox_8.setText(_translate("MainWindow", "Боевик"))
        self.checkBox_9.setText(_translate("MainWindow", "Детектив"))
        self.checkBox.setText(_translate("MainWindow", "Манга"))
        self.checkBox_10.setText(_translate("MainWindow", "Программирование"))
        self.checkBox_11.setText(_translate("MainWindow", "Математика"))
        self.checkBox_12.setText(_translate("MainWindow", "Базы и банки данных. субд"))
        self.label.setText(_translate("MainWindow", "Книги"))
        self.btn_clear_images.setText(_translate("MainWindow", "Очистить изображения"))
        self.rating.setText(_translate("MainWindow", "Автор:"))
        self.style.setText(_translate("MainWindow", "Жанр:"))
        self.date.setText(_translate("MainWindow", "Релиз: "))
        self.date_2.setText(_translate("MainWindow", "Том:"))


class Film_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 976)
        MainWindow.setStyleSheet("selection-background-color:  qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(86, 151, 198, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(670, -10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_exit_films = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_films.setGeometry(QtCore.QRect(20, 0, 51, 23))
        self.btn_exit_films.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_exit_films.setObjectName("btn_exit_films")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.btn_main_criterias = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.btn_main_criterias.setContentsMargins(0, 0, 0, 0)
        self.btn_main_criterias.setObjectName("btn_main_criterias")
        self.btn_date_output = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_date_output.setStyleSheet("border-radius: 15px; border: 3px solid white;\n"
"border-color: rgb(225, 225, 225);\n"
"")
        self.btn_date_output.setObjectName("btn_date_output")
        self.btn_main_criterias.addWidget(self.btn_date_output)
        self.btn_name_output = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_name_output.setStyleSheet("border-radius: 15px; border: 3px solid white;\n"
"border-color: rgb(225, 225, 225);")
        self.btn_name_output.setObjectName("btn_name_output")
        self.btn_main_criterias.addWidget(self.btn_name_output)
        self.btn_rating_output = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_rating_output.setStyleSheet("border-radius: 15px; border: 3px solid white;\n"
"border-color: rgb(225, 225, 225);\n"
"")
        self.btn_rating_output.setObjectName("btn_rating_output")
        self.btn_main_criterias.addWidget(self.btn_rating_output)
        self.table_films = QtWidgets.QListWidget(self.centralwidget)
        self.table_films.setGeometry(QtCore.QRect(330, 510, 501, 471))
        self.table_films.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_films.setStyleSheet("\n"
"background-color: rgba(86, 151, 198, 255)\n"
"")
        self.table_films.setObjectName("table_films")
        self.table_description_films = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.table_description_films.setGeometry(QtCore.QRect(10, 740, 321, 291))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_description_films.setFont(font)
        self.table_description_films.setStyleSheet("\n"
"background-color: rgba(86, 151, 198, 255)")
        self.table_description_films.setReadOnly(True)
        self.table_description_films.setObjectName("table_description_films")
        self.input_search_films = QtWidgets.QLineEdit(self.centralwidget)
        self.input_search_films.setGeometry(QtCore.QRect(340, 30, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.input_search_films.setFont(font)
        self.input_search_films.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_search_films.setToolTipDuration(-1)
        self.input_search_films.setAutoFillBackground(False)
        self.input_search_films.setStyleSheet("border-radius: 10;")
        self.input_search_films.setObjectName("input_search_films")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 90, 321, 641))
        self.widget.setObjectName("widget")
        self.image_films = QtWidgets.QLabel(self.widget)
        self.image_films.setGeometry(QtCore.QRect(10, 30, 301, 441))
        self.image_films.setStyleSheet("\n"
"background-color: rgba(86, 151, 198, 255)")
        self.image_films.setText("")
        self.image_films.setObjectName("image_films")
        self.description = QtWidgets.QLabel(self.widget)
        self.description.setGeometry(QtCore.QRect(10, 620, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.description.setFont(font)
        self.description.setObjectName("description")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 105, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.requests_film = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.requests_film.setContentsMargins(0, 0, 0, 0)
        self.requests_film.setObjectName("requests_film")
        self.rating_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rating_films.setFont(font)
        self.rating_films.setObjectName("rating_films")
        self.requests_film.addWidget(self.rating_films)
        self.nation_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nation_films.setFont(font)
        self.nation_films.setObjectName("nation_films")
        self.requests_film.addWidget(self.nation_films)
        self.style_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.style_films.setFont(font)
        self.style_films.setObjectName("style_films")
        self.requests_film.addWidget(self.style_films)
        self.age_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.age_films.setFont(font)
        self.age_films.setObjectName("age_films")
        self.requests_film.addWidget(self.age_films)
        self.date_films = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.date_films.setFont(font)
        self.date_films.setObjectName("date_films")
        self.requests_film.addWidget(self.date_films)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.requests_film.addWidget(self.label_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 470, 141, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.output_film = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.output_film.setContentsMargins(0, 0, 9, 0)
        self.output_film.setObjectName("output_film")
        self.output_rating_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_rating_films.setStyleSheet("")
        self.output_rating_films.setText("")
        self.output_rating_films.setObjectName("output_rating_films")
        self.output_film.addWidget(self.output_rating_films)
        self.output_nation_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_nation_films.setStyleSheet("")
        self.output_nation_films.setText("")
        self.output_nation_films.setObjectName("output_nation_films")
        self.output_film.addWidget(self.output_nation_films)
        self.output_style_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_style_films.setStyleSheet("")
        self.output_style_films.setText("")
        self.output_style_films.setObjectName("output_style_films")
        self.output_film.addWidget(self.output_style_films)
        self.output_age_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_age_films.setStyleSheet("")
        self.output_age_films.setText("")
        self.output_age_films.setObjectName("output_age_films")
        self.output_film.addWidget(self.output_age_films)
        self.output_date_films = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_date_films.setStyleSheet("")
        self.output_date_films.setText("")
        self.output_date_films.setObjectName("output_date_films")
        self.output_film.addWidget(self.output_date_films)
        self.output_reg = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.output_reg.setText("")
        self.output_reg.setObjectName("output_reg")
        self.output_film.addWidget(self.output_reg)
        self.name_film = QtWidgets.QLabel(self.widget)
        self.name_film.setGeometry(QtCore.QRect(10, 0, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_film.setFont(font)
        self.name_film.setObjectName("name_film")
        self.btn_clear_film_images = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_film_images.setGeometry(QtCore.QRect(80, 0, 131, 23))
        self.btn_clear_film_images.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_clear_film_images.setObjectName("btn_clear_film_images")
        self.widget_film_trailer = QVideoWidget(self.centralwidget)
        self.widget_film_trailer.setGeometry(QtCore.QRect(340, 100, 501, 271))
        self.widget_film_trailer.setStyleSheet("border-radius: 10px; \n"
"border: 3px solid white;\n"
"border-color: rgb(225, 225, 225);\n"
"background-color: rgba(86, 151, 198, 255)")
        self.widget_film_trailer.setObjectName("widget_film_trailer")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 380, 491, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color: rgba(86, 151, 198, 255)")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color: rgba(86, 151, 198, 255)")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 50)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout.addWidget(self.horizontalSlider_2)
        self.ready_for_viewing = QtWidgets.QLabel(self.centralwidget)
        self.ready_for_viewing.setGeometry(QtCore.QRect(370, 80, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ready_for_viewing.setFont(font)
        self.ready_for_viewing.setText("")
        self.ready_for_viewing.setObjectName("ready_for_viewing")
        self.btn_clear_trailers = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_trailers.setGeometry(QtCore.QRect(220, 0, 121, 23))
        self.btn_clear_trailers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_clear_trailers.setObjectName("btn_clear_trailers")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, -8, 901, 961))
        self.bg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(86, 151, 198, 255), stop:1 rgba(255, 255, 255, 255))")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(340, 410, 501, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.categories_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.categories_3.setContentsMargins(0, 0, 0, 0)
        self.categories_3.setObjectName("categories_3")
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.categories_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.categories_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_8.setObjectName("checkBox_8")
        self.categories_3.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.categories_3.addWidget(self.checkBox_9)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(340, 480, 95, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(410, 480, 120, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(510, 480, 162, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(590, 480, 71, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(720, 480, 101, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.bg.raise_()
        self.label.raise_()
        self.btn_exit_films.raise_()
        self.horizontalLayoutWidget.raise_()
        self.table_films.raise_()
        self.table_description_films.raise_()
        self.input_search_films.raise_()
        self.widget.raise_()
        self.btn_clear_film_images.raise_()
        self.widget_film_trailer.raise_()
        self.layoutWidget.raise_()
        self.ready_for_viewing.raise_()
        self.btn_clear_trailers.raise_()
        self.layoutWidget_2.raise_()
        self.checkBox.raise_()
        self.checkBox_5.raise_()
        self.checkBox_3.raise_()
        self.checkBox_2.raise_()
        self.checkBox_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Фильмы."))
        self.btn_exit_films.setText(_translate("MainWindow", "Назад"))
        self.btn_date_output.setText(_translate("MainWindow", "По дате"))
        self.btn_name_output.setText(_translate("MainWindow", "По названию"))
        self.btn_rating_output.setText(_translate("MainWindow", "По рейтингу"))
        self.input_search_films.setText(_translate("MainWindow", "Поиск...."))
        self.description.setText(_translate("MainWindow", "Описание:"))
        self.rating_films.setText(_translate("MainWindow", "Рейтинг: "))
        self.nation_films.setText(_translate("MainWindow", "Страна:"))
        self.style_films.setText(_translate("MainWindow", "Жанры:"))
        self.age_films.setText(_translate("MainWindow", "Возраст:"))
        self.date_films.setText(_translate("MainWindow", "Релиз: "))
        self.label_3.setText(_translate("MainWindow", "Режиссер:"))
        self.name_film.setText(_translate("MainWindow", "Фильм"))
        self.btn_clear_film_images.setText(_translate("MainWindow", "Очистить Изображения"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить Трейлер"))
        self.label_2.setText(_translate("MainWindow", "Громкость"))
        self.btn_clear_trailers.setText(_translate("MainWindow", "Очистить трейлеры"))
        self.checkBox_6.setText(_translate("MainWindow", "Детектив"))
        self.checkBox_7.setText(_translate("MainWindow", "Комедия"))
        self.checkBox_8.setText(_translate("MainWindow", "Криминал"))
        self.checkBox_9.setText(_translate("MainWindow", "Фантастика"))
        self.checkBox.setText(_translate("MainWindow", "Боевик"))
        self.checkBox_5.setText(_translate("MainWindow", "Фэнтези"))
        self.checkBox_3.setText(_translate("MainWindow", "Драма"))
        self.checkBox_2.setText(_translate("MainWindow", "Триллер"))
        self.checkBox_4.setText(_translate("MainWindow", "Мультфильм"))
from PyQt5.QtMultimediaWidgets import QVideoWidget

class Main_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 298)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 391, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_films = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_films.setObjectName("btn_films")
        self.horizontalLayout.addWidget(self.btn_films)
        self.btn_books_and_comics = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_books_and_comics.setObjectName("btn_books_and_comics")
        self.horizontalLayout.addWidget(self.btn_books_and_comics)
        self.btn_serials = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_serials.setObjectName("btn_serials")
        self.horizontalLayout.addWidget(self.btn_serials)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(10, 130, 191, 23))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_settings.setGeometry(QtCore.QRect(200, 130, 191, 23))
        self.btn_settings.setObjectName("btn_settings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выберите категорию"))
        self.btn_films.setText(_translate("MainWindow", "Фильмы"))
        self.btn_books_and_comics.setText(_translate("MainWindow", "Книги и комиксы"))
        self.btn_serials.setText(_translate("MainWindow", "Сериалы"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
        self.btn_settings.setText(_translate("MainWindow", "Настройки"))
